### ISSUE TITLE
Erreur lors de l'affichage des scripts

### ISSUE THREAD

**Issue by MathildeChan** [MathildeChan/Spingboot-tds#1]
https://github.com/MathildeChan/Spingboot-tds/blob/362daa71ca802e29adafb25ca964520b1f79b73f/src/main/java/s4/TD5/controllers/LogController.java#L37-L46

Je ne sais pas vraiment d'où provient l'erreur. Tout marchait très bien jusqu'à ce que je souhaite afficher les scripts par utilisateur. Tout port à croire que je n'ai pas besoin d'un findByUser pour mes scripts car ils sont déjà dans les données de l'utilisateurs. Je n'arrive cependant pas à les afficher. 

On m'affiche cette erreur : 
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: s4.TD5.models.User.scripts, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:606) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:387) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]

J'ai fait beaucoup de test, ma variable de session n'est pas vide je ne sais plus quoi faire.

**Comment by jcheron** [comment]
Par défaut, le fetch des objets associés est en mode LAZY, c'est à dire chargés seulement à la demande (quand on fait un `getScripts` sur le user par exemple).
C'est ce que vous essayez de faire ici, mais ça ne fonctionne pas. Ca ne peut fonctionner que si l'instance est encore attachée à l'entity manager, or ici, ce n'est plus le cas, c'est une instance détachée qui est en session.

Pour résoudre le pb, il faut passer le fetchMode en `EAGER`, pour faire en sorte que les scripts soient chargés en même temps que le user.

https://github.com/MathildeChan/Spingboot-tds/blob/362daa71ca802e29adafb25ca964520b1f79b73f/src/main/java/s4/TD5/models/User.java#L17-L18

A modifier par:
```java
 @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.ALL) 
 private List<Script> scripts; 
```

**Comment by MathildeChan** [comment]
Problème résolu ! Tout fonctionne de nouveau. Merci !
